spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${AZURE_DB_URL}
    username: ${AZURE_DB_USER}
    password: ${AZURE_DB_PASSWORD}

  jpa:
    # Showing log for each sql query
    show-sql: true
    open-in-view: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
